AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache
      SubnetIds:
        - subnet-02c217f126c0ce1d5

  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          REDIS_HOST: !GetAtt MyElasticacheRedis.RedisEndpoint.Address
      VpcConfig:
        SubnetIds:
          - subnet-02c217f126c0ce1d5
        SecurityGroupIds:
          - !GetAtt MySecurityGroup.GroupId
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: any
        CustomersPath:
          Type: Api
          Properties:
            Path: /customers
            Method: any
        CustomersByPhonePath:
          Type: Api
          Properties:
            Path: /customers/{phoneNumber}
            Method: any
        OrdersPath:
          Type: Api
          Properties:
            Path: /orders
            Method: any
        OrdersByIdPath:
          Type: Api
          Properties:
            Path: /orders/{orderId}
            Method: any
        OrderItemsPath:
          Type: Api
          Properties:
            Path: /orderItems
            Method: any
        OrderItemsByIdPath:
          Type: Api
          Properties:
            Path: /orderItems/{orderItemId}
            Method: any




     

  